#-------------------------------
# General Site Settings

title: Rohan Mehrotra
url: "https://rdmehrotra.github.io"
baseurl: "/personalwebsite"

remote_theme: artemsheludko/norlin
#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  style: compressed
