#-------------------------------
# Site Settings
title: Rohan Mehrotra
logo:
description: Norlin – A Beautiful Dark Blog Theme for Jekyll.

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Resume'
      url: '/resume/'
    - title: 'Contact Me'
      url: '/contact/'
    - title: 'Style Guide'
      url: '/styleguide/'

#-------------------------------
# Author Settings
author:
  name: Rohan Mehrotra
  avatar: '/images/15.jpg'

#-------------------------------
# Hero Settings
hero:
  title: Rohan Mehrotra
  description: Electrical Engineering @ Georgia Tech
  image: '/images/01.jpg'
